# #     if: ${{ github.event.label.name == 'major' || github.event.label.name == 'minor' || github.event.label.name == 'patch'}}

#       - name: Print Context
#         env:
#           github: ${{ toJSON(github) }}
#         run: |
#           echo $github
