name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    # if: |
    #   (
    #     contains(github.event.pull_request.labels.*.name, 'patch') ||
    #     contains(github.event.pull_request.labels.*.name, 'minor') ||
    #     contains(github.event.pull_request.labels.*.name, 'major')
    #   )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config user.name 'github-action'
          git config user.email 'github-actions@github.com'

      - name: Build From Source
        run: npx tsc

      - name: Version Bump
        env:
          new_version: |
            ${{
              contains(github.event.pull_request.labels.*.name, 'major') && 'major' ||
              contains(github.event.pull_request.labels.*.name, 'minor') && 'minor' ||
              contains(github.event.pull_request.labels.*.name, 'patch') && 'patch'
            }}
        # run: npm version $new_version
        run: npm version patch

      - name: Commit New Version
        run: |
          git checkout -b "release/$(git log -n 1 --pretty=%s)"
          git push origin HEAD
