name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print github
        env:
          json_github: ${{ toJSON(github) }}
        run: |
          echo $json_github

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          # Needed to trigger release/* events
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # "events triggered by the GITHUB_TOKEN ... will not create a new workflow run"
          token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Configure git
        run: |
          git config user.name 'github-action'
          git config user.email 'github-actions@github.com'

      - name: Get next version
        uses: actions/github-script@v6
        id: latest-version
        with:
          result-encoding: string
          script: |
            semver.inc('v1.2.3', 'patch');
            const result = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: 'latest',
            });
            return result.data.name

      - name: Bump version
        env:
          level: |
            ${{
              contains(github.event.pull_request.labels.*.name, 'major') && 'major' ||
              contains(github.event.pull_request.labels.*.name, 'minor') && 'minor' ||
              contains(github.event.pull_request.labels.*.name, 'patch') && 'patch' || ''
            }}
        run: |
          npm version $(npx semver -i $level ${{ steps.latest-version.outputs.result }}) --git-tag-version=false

      - name: Commit release branch
        run: |
          git add -A
          git commit -m ${{ env.new_version }}
          git checkout -b "release/${{ env.new_version }}"
          git push origin HEAD
