name: "Build"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: npm install
      - run: npm run build
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add -f dist
      - run: git commit -m "dist files"
      - run: git push -f
