name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    # if: |
    #   (
    #     contains(github.event.pull_request.labels.*.name, 'patch') ||
    #     contains(github.event.pull_request.labels.*.name, 'minor') ||
    #     contains(github.event.pull_request.labels.*.name, 'major')
    #   )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Configure git
        run: |
          git config user.name 'github-action'
          git config user.email 'github-actions@github.com'

      - name: Build from source
        run: npx tsc

      - name: Version bump
        env:
          new_version: |
            ${{
              contains(github.event.pull_request.labels.*.name, 'major') && 'major' ||
              contains(github.event.pull_request.labels.*.name, 'minor') && 'minor' ||
              contains(github.event.pull_request.labels.*.name, 'patch') && 'patch'
            }}
        # run: npm version $new_version
        run: npm version patch

      - name: Create release branch
        run: |
          git push
