name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        env:
          github: ${{ toJSON(github) }}
        run: |
          echo $github

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Configure git
        run: |
          git config user.name 'github-action'
          git config user.email 'github-actions@github.com'

      - name: Build from source
        run: |
          npx tsc
          git add -A
          git commit -m build

      - name: Bump version
        env:
          level: |
            ${{
              contains(github.event.pull_request.labels.*.name, 'major') && 'major' ||
              contains(github.event.pull_request.labels.*.name, 'minor') && 'minor' ||
              contains(github.event.pull_request.labels.*.name, 'patch') && 'patch'
            }}
        # run: npm version $new_version
        run: |
          npm version $(npx semver -i $level 1.0.0)

      - name: Commit release branch
        run: |
          git checkout -b "release/$(git describe)"
          git push origin HEAD
