name: "Distribution"

on:
  push:
    # types: [closed]
    branches:
      - "main"

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install
        run: npm install

      - name: Configuration
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Versioning
        run: |
          npm version patch --git-tag-version=false
          git add package.json package-lock.json

      - name: Build
        run: |
          npm run build
          git add --force dist

      - name: Commit
        run: |
          git checkout -b v$(npm pkg get version | sed 's/"//g')
          git add --all
          git commit --message 'CI Build'
          git push origin HEAD
