name: "Distribution"

on:
  push:
    branches:
      - "main"

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}
          # fetch-depth: 0
          # ref: ${{ github.event.push.head.ref }}/

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install
        run: |
          npm install
          git config user.name github-actions
          git config user.email github-actions@github.com

          npm version patch
          git add package.json
          
          git push

      # git commit -m "Distribution Build"
      # git checkout -b release
      # npm run build
      # git add -f dist
      # - name: Version Bump
      # run: |
      # - name: Build
      # run: |
      # - name: "Push"
      # run: |
      # - name: Build
      # git commit -m "Distribution Build"
      # run: |
      # npm run build
      # git add -f dist

      # - run: git push
