name: "Distribution"

on:
  push:
    # types: [closed]
    branches:
      - "main"

jobs:
  distribution:
    if: github.event.push.pusher.name != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      -run: echo ${{ github.event.push.pusher.name }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install
        run: npm install

      - name: Version Bump
        run: |
          npm version patch --git-tag-version=false

      - name: Build Source
        run: |
          npm run build

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m $(npm pkg get version | sed 's/"//g')
          git push
