name: "Distribution"

on:
  push:
    # types: [closed]
    branches:
      - "main"

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install
        run: npm install

      - name: Version Bump
        run: |
          npm version patch --git-tag-version=false

      - name: Build Source
        run: |
          npm run build

      - name: Commit
        env:
          version: $(npm pkg get version | sed 's/"//g')
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b $version
          git add --all
          git commit --message $versiong
          git push
