name: "Distribution"

on:
  push:
    # types: [closed]
    branches:
      - "main"

env:
  git_name: github-actions
  git_email: github-actions@github.com

jobs:
  distribution:
    # Only steps have access to environment variables.
    if: github.event.head_commit.author.name != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Print github
        env:
          CTX: ${{ toJSON(github) }}
        run: echo "$CTX"

      - name: Install
        run: npm install

      - name: Versioning
        run: |
          npm version patch --git-tag-version=false

      - name: Build
        run: |
          npm run build

      - name: Commit
        run: |
          git config user.name "$git_name"
          git config user.email "$git_email"
          git add --all
          git commit --message v$(npm pkg get version | sed 's/"//g')
          git push
