on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  distribution:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Configuration
        run: |
          npm install
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Version Bump
        run: |
          npm version patch
          git add package.json

      - name: "Commit"
        run: |
          git commit -m "Distribution Build"
          git push

      # - name: Build
      # run: |
      # npm run build
      # git add -f dist

      # - run: git push
