name: "Distribution"

on:
  push:
    branches:
      - "main"

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        # token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Configuration
        run: |
          npm install
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Version Bump
        run: |
          npm version patch
          npm run build
          git add package.json

      - run: git push

      # - name: "Commit"
      # run: git commit -m "Distribution Build"

      # - name: Build
      # run: |
      # npm run build
      # git add -f dist

      # - run: git push
