name: "Publish"

on:
  create:
    branches:
      - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}"
          script: |
            await github.rest.repos.createRelease({
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: process.env.RELEASE_TAG,
               tag_name: process.env.RELEASE_TAG,
            });
