name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ contains(join(github.event.pull_request.labels.*.name), 'release/') }}fdsaf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - run: npm install

      - name: Get release version
        uses: actions/github-script@v6
        id: release-version
        with:
          result-encoding: string
          script: |
            const semver = require("semver");
            const labels = JSON.parse("${{ toJson(github.event.pull_request.labels) }}");
            const label = labels.find((label) => label.name.startsWith("release/"));
            const [,release] = label.name.split("/", 2);
            if (!release) {
              throw Error("Release label not detected")
            }
            const result = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: "latest",
            });
            const releaseVersion = semver.inc(result.data.tag_name, release);
            if (!releaseVersion) {
              throw Error("Release version could not be generated")
            }
            return releaseVersion;

      - name: Bump version
        run: |
          npm version ${{ steps.release-version.outputs.result }} --git-tag-version=false

      - name: Commit release branch
        run: |
          git config user.name 'github-action'
          git config user.email 'github-actions@github.com'
          git add -A
          git commit -m '${{ steps.release-version.outputs.result }}'
          git checkout -b '${{ steps.release-version.outputs.result }}'
          git push origin HEAD

      - name: Create release
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ steps.release-version.outputs.result }}",
              prerelease: "${{ steps.release-version.outputs.result }}".includes("-"),
            });
