name: "Publish"

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  distribution:
    if: |
      github.event.pull_request.merged == true &&
      (
        contains(github.event.issue.labels.*.name, 'patch') ||
        contains(github.event.issue.labels.*.name, 'minor') ||
        contains(github.event.issue.labels.*.name, 'major')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Print github
        env:
          github: ${{ toJSON(github) }}
        run: echo "$github"

      - name: Install
        run: npm install

      - name: Versioning
        env:
          p: ${{ contains(github.event.issue.labels.*.name, 'patch') }}
          n: ${{ contains(github.event.issue.labels.*.name, 'minor') }}
          j: ${{ contains(github.event.issue.labels.*.name, 'major') }}
          patch: ${{ contains(github.event.issue.labels.*.name, 'patch') && 'patch' || '-' }}
          minor: ${{ contains(github.event.issue.labels.*.name, 'minor') && 'minor' || '-' }}
          major: ${{ contains(github.event.issue.labels.*.name, 'major') && 'major' || '-' }}
          version_bump: |
            ${{
              contains(github.event.issue.labels.*.name, 'patch') && 'patch' ||
              contains(github.event.issue.labels.*.name, 'minor') && 'minor' ||
              contains(github.event.issue.labels.*.name, 'major') && 'major' || '-'
            }}
        run: npm version "$version_bump" --git-tag-version=false

      - name: Build
        run: npm run build

      - name: Commit
        env:
          current_version: $(npm pkg get version | sed 's/"//g')
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add --all
          git commit --message "v$current_version"
          git push
