name: "Publish"

on:
  push:
    branches:
      - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Print github
        env:
          github: ${{ toJSON(github) }}
        run: |
          echo $github

      - name: Create release
        run: |
          curl https://api.github.com/repos/${{ github.repository }}/releases \
            -s \
            --fail-with-body \
            -X POST \
            -H 'Authorization: Bearer ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}' \
            -d '{
              "name": "v.1.2.3",
              "tag_name": "v1.2.3",
              "target_commitish": "${{ github.ref_name }}"
            }'
