name: "Publish"

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  distribution:
    if: |
      github.event.pull_request.merged == true &&
      (
        contains(github.event.pull_request.labels.*.name, 'patch') ||
        contains(github.event.pull_request.labels.*.name, 'minor') ||
        contains(github.event.pull_request.labels.*.name, 'major')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install
        run: npm install

      - name: Versioning
        env:
          version_bump: |
            ${{
              contains(github.event.pull_request.labels.*.name, 'patch') && 'patch' ||
              contains(github.event.pull_request.labels.*.name, 'minor') && 'minor' ||
              contains(github.event.pull_request.labels.*.name, 'major') && 'major' || '-'
            }}
        run: npm version $version_bump --git-tag-version=false

      - name: Build
        run: npm run build

      - name: Commit
        env:
          current_version: $(npm pkg get version | sed 's/"//g')
        run: |
          git config user.name github-action
          git config user.email github-actions@github.com
          git add --all
          git commit --message v$current_version
          git push
