name: "Testing"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "main"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: "Configuration"
        run: npm install

      - name: Formatting Checks
        run: npm run format:ci

      - name: Unit Tests
        run: npm run test:ci

      - name: Build Time Validation
        run: npm run build:ci
