name: "Bump Versioning"

on:
  pull_request:
    types: [labeled]
    branches:
      - "main"

jobs:
  bump:
    if: ${{ github.event.label.name == 'major' ||  github.event.label.name == 'minor' || github.event.label.name == 'patch'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: |
          npm version ${{ github.event.label.name }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json
          git commit -m "Version Bump (${{ github.event.label.name }})"
          git push
