name: "Bump Versioning"

on:
  pull_request:
    types: [labeled]
    branches:
      - "*"
      - "!main"

jobs:
  patch:
    # if: ${{ github.event.label.name == "patch" }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: npm version patch
      - run: git add package.json
      - run: git commit -m "Patch Version Bump"
      - run: git push origin HEAD"
